# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Upgrade_Windows.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Upgrade_Tool(object):
    def setupUi(self, Upgrade_Tool):
        Upgrade_Tool.setObjectName("Upgrade_Tool")
        Upgrade_Tool.resize(748, 637)
        self.centralwidget = QtWidgets.QWidget(Upgrade_Tool)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_TCP = QtWidgets.QWidget(self.centralwidget)
        self.widget_TCP.setEnabled(True)
        self.widget_TCP.setAutoFillBackground(True)
        self.widget_TCP.setObjectName("widget_TCP")
        self.label_TCP = QtWidgets.QLabel(self.widget_TCP)
        self.label_TCP.setGeometry(QtCore.QRect(9, 9, 53, 18))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_TCP.setFont(font)
        self.label_TCP.setObjectName("label_TCP")
        self.label_IPPort = QtWidgets.QLabel(self.widget_TCP)
        self.label_IPPort.setGeometry(QtCore.QRect(10, 70, 54, 16))
        self.label_IPPort.setObjectName("label_IPPort")
        self.lineEdit_IPAddr = QtWidgets.QLineEdit(self.widget_TCP)
        self.lineEdit_IPAddr.setGeometry(QtCore.QRect(81, 40, 133, 20))
        self.lineEdit_IPAddr.setObjectName("lineEdit_IPAddr")
        self.lineEdit_IPPort = QtWidgets.QLineEdit(self.widget_TCP)
        self.lineEdit_IPPort.setGeometry(QtCore.QRect(81, 70, 133, 20))
        self.lineEdit_IPPort.setObjectName("lineEdit_IPPort")
        self.label_IPAddr = QtWidgets.QLabel(self.widget_TCP)
        self.label_IPAddr.setGeometry(QtCore.QRect(9, 40, 66, 16))
        self.label_IPAddr.setObjectName("label_IPAddr")
        self.pushButton_TCPConnect = QtWidgets.QPushButton(self.widget_TCP)
        self.pushButton_TCPConnect.setGeometry(QtCore.QRect(9, 190, 75, 23))
        self.pushButton_TCPConnect.setObjectName("pushButton_TCPConnect")
        self.gridLayout_5.addWidget(self.widget_TCP, 0, 0, 1, 1)
        self.widget_UART = QtWidgets.QWidget(self.centralwidget)
        self.widget_UART.setEnabled(True)
        self.widget_UART.setAutoFillBackground(True)
        self.widget_UART.setObjectName("widget_UART")
        self.label_UART = QtWidgets.QLabel(self.widget_UART)
        self.label_UART.setGeometry(QtCore.QRect(9, 9, 60, 18))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_UART.setFont(font)
        self.label_UART.setObjectName("label_UART")
        self.pushButton_UARTConnect = QtWidgets.QPushButton(self.widget_UART)
        self.pushButton_UARTConnect.setGeometry(QtCore.QRect(9, 190, 75, 23))
        self.pushButton_UARTConnect.setObjectName("pushButton_UARTConnect")
        self.pushButton_CheckPort = QtWidgets.QPushButton(self.widget_UART)
        self.pushButton_CheckPort.setGeometry(QtCore.QRect(210, 160, 80, 23))
        self.pushButton_CheckPort.setObjectName("pushButton_CheckPort")
        self.comboBox_Port = QtWidgets.QComboBox(self.widget_UART)
        self.comboBox_Port.setGeometry(QtCore.QRect(90, 70, 61, 20))
        self.comboBox_Port.setObjectName("comboBox_Port")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.comboBox_Port.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_UART)
        self.textBrowser.setGeometry(QtCore.QRect(158, 40, 141, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.comboBox_StopBit = QtWidgets.QComboBox(self.widget_UART)
        self.comboBox_StopBit.setGeometry(QtCore.QRect(90, 130, 61, 20))
        self.comboBox_StopBit.setObjectName("comboBox_StopBit")
        self.comboBox_StopBit.addItem("")
        self.comboBox_StopBit.addItem("")
        self.label_PortSelect = QtWidgets.QLabel(self.widget_UART)
        self.label_PortSelect.setGeometry(QtCore.QRect(9, 70, 60, 16))
        self.label_PortSelect.setObjectName("label_PortSelect")
        self.comboBox_BoundRate = QtWidgets.QComboBox(self.widget_UART)
        self.comboBox_BoundRate.setGeometry(QtCore.QRect(90, 40, 62, 20))
        self.comboBox_BoundRate.setObjectName("comboBox_BoundRate")
        self.comboBox_BoundRate.addItem("")
        self.comboBox_BoundRate.addItem("")
        self.comboBox_BoundRate.addItem("")
        self.comboBox_CRCBit = QtWidgets.QComboBox(self.widget_UART)
        self.comboBox_CRCBit.setEnabled(True)
        self.comboBox_CRCBit.setGeometry(QtCore.QRect(90, 160, 61, 20))
        self.comboBox_CRCBit.setObjectName("comboBox_CRCBit")
        self.comboBox_CRCBit.addItem("")
        self.comboBox_CRCBit.addItem("")
        self.comboBox_CRCBit.addItem("")
        self.comboBox_CRCBit.addItem("")
        self.comboBox_CRCBit.addItem("")
        self.label_BoundRate = QtWidgets.QLabel(self.widget_UART)
        self.label_BoundRate.setGeometry(QtCore.QRect(9, 40, 48, 16))
        self.label_BoundRate.setObjectName("label_BoundRate")
        self.label_Bit = QtWidgets.QLabel(self.widget_UART)
        self.label_Bit.setGeometry(QtCore.QRect(9, 100, 48, 16))
        self.label_Bit.setObjectName("label_Bit")
        self.label_CRCBit = QtWidgets.QLabel(self.widget_UART)
        self.label_CRCBit.setGeometry(QtCore.QRect(9, 160, 36, 16))
        self.label_CRCBit.setObjectName("label_CRCBit")
        self.label_StopBit = QtWidgets.QLabel(self.widget_UART)
        self.label_StopBit.setGeometry(QtCore.QRect(9, 130, 48, 16))
        self.label_StopBit.setObjectName("label_StopBit")
        self.comboBox_Bit = QtWidgets.QComboBox(self.widget_UART)
        self.comboBox_Bit.setGeometry(QtCore.QRect(90, 100, 61, 20))
        self.comboBox_Bit.setObjectName("comboBox_Bit")
        self.comboBox_Bit.addItem("")
        self.comboBox_Bit.addItem("")
        self.comboBox_Bit.addItem("")
        self.gridLayout_5.addWidget(self.widget_UART, 0, 4, 1, 1)
        self.widget_CAN = QtWidgets.QWidget(self.centralwidget)
        self.widget_CAN.setEnabled(True)
        self.widget_CAN.setAutoFillBackground(True)
        self.widget_CAN.setObjectName("widget_CAN")
        self.label_CAN = QtWidgets.QLabel(self.widget_CAN)
        self.label_CAN.setGeometry(QtCore.QRect(9, 9, 53, 18))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_CAN.setFont(font)
        self.label_CAN.setObjectName("label_CAN")
        self.pushButton_CANConnect = QtWidgets.QPushButton(self.widget_CAN)
        self.pushButton_CANConnect.setGeometry(QtCore.QRect(9, 190, 75, 23))
        self.pushButton_CANConnect.setObjectName("pushButton_CANConnect")
        self.comboBox_CANDevice = QtWidgets.QComboBox(self.widget_CAN)
        self.comboBox_CANDevice.setGeometry(QtCore.QRect(90, 40, 71, 20))
        self.comboBox_CANDevice.setObjectName("comboBox_CANDevice")
        self.comboBox_CANDevice.addItem("")
        self.comboBox_CANDevice.addItem("")
        self.comboBox_CANBoundRate = QtWidgets.QComboBox(self.widget_CAN)
        self.comboBox_CANBoundRate.setGeometry(QtCore.QRect(90, 130, 71, 20))
        self.comboBox_CANBoundRate.setObjectName("comboBox_CANBoundRate")
        self.comboBox_CANBoundRate.addItem("")
        self.comboBox_CANBoundRate.addItem("")
        self.comboBox_CANBoundRate.addItem("")
        self.comboBox_CANBoundRate.addItem("")
        self.comboBox_CANBoundRate.addItem("")
        self.comboBox_CANBoundRate.addItem("")
        self.comboBox_CANBoundRate.addItem("")
        self.comboBox_CANBoundRate.addItem("")
        self.label_CANChannel = QtWidgets.QLabel(self.widget_CAN)
        self.label_CANChannel.setGeometry(QtCore.QRect(9, 100, 36, 16))
        self.label_CANChannel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_CANChannel.setObjectName("label_CANChannel")
        self.comboBox_CANChannel = QtWidgets.QComboBox(self.widget_CAN)
        self.comboBox_CANChannel.setGeometry(QtCore.QRect(90, 100, 71, 20))
        self.comboBox_CANChannel.setObjectName("comboBox_CANChannel")
        self.comboBox_CANChannel.addItem("")
        self.comboBox_CANChannel.addItem("")
        self.label_CANBoundRate = QtWidgets.QLabel(self.widget_CAN)
        self.label_CANBoundRate.setGeometry(QtCore.QRect(9, 130, 36, 16))
        self.label_CANBoundRate.setObjectName("label_CANBoundRate")
        self.comboBox_CANIndex = QtWidgets.QComboBox(self.widget_CAN)
        self.comboBox_CANIndex.setGeometry(QtCore.QRect(90, 70, 71, 20))
        self.comboBox_CANIndex.setObjectName("comboBox_CANIndex")
        self.comboBox_CANIndex.addItem("")
        self.comboBox_CANIndex.addItem("")
        self.comboBox_CANIndex.addItem("")
        self.comboBox_CANIndex.addItem("")
        self.comboBox_CANIndex.addItem("")
        self.comboBox_CANIndex.addItem("")
        self.comboBox_CANIndex.addItem("")
        self.comboBox_CANIndex.addItem("")
        self.label_CANDevice = QtWidgets.QLabel(self.widget_CAN)
        self.label_CANDevice.setGeometry(QtCore.QRect(9, 40, 42, 16))
        self.label_CANDevice.setObjectName("label_CANDevice")
        self.label_CANIndex = QtWidgets.QLabel(self.widget_CAN)
        self.label_CANIndex.setGeometry(QtCore.QRect(9, 70, 60, 16))
        self.label_CANIndex.setObjectName("label_CANIndex")
        self.gridLayout_5.addWidget(self.widget_CAN, 0, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 1, 0, 1, 5)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_5.addWidget(self.line_5, 0, 3, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_FileVersion = QtWidgets.QLabel(self.centralwidget)
        self.label_FileVersion.setObjectName("label_FileVersion")
        self.gridLayout_4.addWidget(self.label_FileVersion, 5, 1, 1, 2)
        self.checkBox_Module5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module5.setObjectName("checkBox_Module5")
        self.gridLayout_4.addWidget(self.checkBox_Module5, 9, 5, 1, 1)
        self.checkBox_Module20 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module20.setObjectName("checkBox_Module20")
        self.gridLayout_4.addWidget(self.checkBox_Module20, 12, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 7, 1, 1, 5)
        self.label_FileSize = QtWidgets.QLabel(self.centralwidget)
        self.label_FileSize.setObjectName("label_FileSize")
        self.gridLayout_4.addWidget(self.label_FileSize, 4, 1, 1, 2)
        self.checkBox_Module17 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module17.setObjectName("checkBox_Module17")
        self.gridLayout_4.addWidget(self.checkBox_Module17, 12, 2, 1, 1)
        self.checkBox_Module16 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module16.setObjectName("checkBox_Module16")
        self.gridLayout_4.addWidget(self.checkBox_Module16, 12, 1, 1, 1)
        self.label_Load = QtWidgets.QLabel(self.centralwidget)
        self.label_Load.setObjectName("label_Load")
        self.gridLayout_4.addWidget(self.label_Load, 2, 2, 1, 4)
        self.checkBox_Module18 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module18.setObjectName("checkBox_Module18")
        self.gridLayout_4.addWidget(self.checkBox_Module18, 12, 3, 1, 1)
        self.checkBox_Module9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module9.setObjectName("checkBox_Module9")
        self.gridLayout_4.addWidget(self.checkBox_Module9, 10, 4, 1, 1)
        self.checkBox_AllUp = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_AllUp.setObjectName("checkBox_AllUp")
        self.gridLayout_4.addWidget(self.checkBox_AllUp, 8, 5, 1, 1)
        self.pushButton_StartUpgrade = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StartUpgrade.setObjectName("pushButton_StartUpgrade")
        self.gridLayout_4.addWidget(self.pushButton_StartUpgrade, 14, 1, 1, 1)
        self.checkBox_Module3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module3.setObjectName("checkBox_Module3")
        self.gridLayout_4.addWidget(self.checkBox_Module3, 9, 3, 1, 1)
        self.checkBox_Module11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module11.setObjectName("checkBox_Module11")
        self.gridLayout_4.addWidget(self.checkBox_Module11, 11, 1, 1, 1)
        self.checkBox_SelectAll = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_SelectAll.setObjectName("checkBox_SelectAll")
        self.gridLayout_4.addWidget(self.checkBox_SelectAll, 13, 5, 1, 1)
        self.checkBox_Module10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module10.setObjectName("checkBox_Module10")
        self.gridLayout_4.addWidget(self.checkBox_Module10, 10, 5, 1, 1)
        self.checkBox_Module12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module12.setObjectName("checkBox_Module12")
        self.gridLayout_4.addWidget(self.checkBox_Module12, 11, 2, 1, 1)
        self.label_FileCRC = QtWidgets.QLabel(self.centralwidget)
        self.label_FileCRC.setObjectName("label_FileCRC")
        self.gridLayout_4.addWidget(self.label_FileCRC, 4, 3, 1, 3)
        self.checkBox_Module7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module7.setObjectName("checkBox_Module7")
        self.gridLayout_4.addWidget(self.checkBox_Module7, 10, 2, 1, 1)
        self.checkBox_Module13 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module13.setObjectName("checkBox_Module13")
        self.gridLayout_4.addWidget(self.checkBox_Module13, 11, 3, 1, 1)
        self.checkBox_Module8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module8.setObjectName("checkBox_Module8")
        self.gridLayout_4.addWidget(self.checkBox_Module8, 10, 3, 1, 1)
        self.comboBox_SelcectZC = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_SelcectZC.setObjectName("comboBox_SelcectZC")
        self.comboBox_SelcectZC.addItem("")
        self.comboBox_SelcectZC.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_SelcectZC, 8, 1, 1, 1)
        self.checkBox_Module19 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module19.setObjectName("checkBox_Module19")
        self.gridLayout_4.addWidget(self.checkBox_Module19, 12, 4, 1, 1)
        self.checkBox_Module4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module4.setObjectName("checkBox_Module4")
        self.gridLayout_4.addWidget(self.checkBox_Module4, 9, 4, 1, 1)
        self.pushButton_OpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OpenFile.setObjectName("pushButton_OpenFile")
        self.gridLayout_4.addWidget(self.pushButton_OpenFile, 2, 1, 1, 1)
        self.checkBox_Module2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module2.setObjectName("checkBox_Module2")
        self.gridLayout_4.addWidget(self.checkBox_Module2, 9, 2, 1, 1)
        self.checkBox_Module6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module6.setObjectName("checkBox_Module6")
        self.gridLayout_4.addWidget(self.checkBox_Module6, 10, 1, 1, 1)
        self.checkBox_Module15 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module15.setObjectName("checkBox_Module15")
        self.gridLayout_4.addWidget(self.checkBox_Module15, 11, 5, 1, 1)
        self.checkBox_OneUp = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_OneUp.setObjectName("checkBox_OneUp")
        self.gridLayout_4.addWidget(self.checkBox_OneUp, 8, 4, 1, 1)
        self.checkBox_Module14 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Module14.setObjectName("checkBox_Module14")
        self.gridLayout_4.addWidget(self.checkBox_Module14, 11, 4, 1, 1)
        self.checkBox_Module1 = QtWidgets.QCheckBox(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.checkBox_Module1.setPalette(palette)
        self.checkBox_Module1.setAutoFillBackground(True)
        self.checkBox_Module1.setObjectName("checkBox_Module1")
        self.gridLayout_4.addWidget(self.checkBox_Module1, 9, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 14, 2, 1, 4)
        self.pushButton_SaveRecord = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SaveRecord.setObjectName("pushButton_SaveRecord")
        self.gridLayout_4.addWidget(self.pushButton_SaveRecord, 14, 9, 1, 1)
        self.textBrowser_UpgradeRecord = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_UpgradeRecord.setMinimumSize(QtCore.QSize(318, 291))
        self.textBrowser_UpgradeRecord.setObjectName("textBrowser_UpgradeRecord")
        self.gridLayout_4.addWidget(self.textBrowser_UpgradeRecord, 2, 6, 12, 4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 1, 1, 9)
        self.label_CommInfo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_CommInfo.setFont(font)
        self.label_CommInfo.setObjectName("label_CommInfo")
        self.gridLayout_4.addWidget(self.label_CommInfo, 0, 1, 1, 9)
        self.gridLayout_4.setRowMinimumHeight(2, 30)
        self.gridLayout_4.setRowMinimumHeight(8, 30)
        self.gridLayout_4.setRowMinimumHeight(9, 30)
        self.gridLayout_4.setRowMinimumHeight(10, 30)
        self.gridLayout_4.setRowMinimumHeight(11, 30)
        self.gridLayout_4.setRowMinimumHeight(12, 30)
        self.gridLayout_4.setRowMinimumHeight(13, 30)
        self.gridLayout_4.setRowMinimumHeight(14, 30)
        self.gridLayout_5.addLayout(self.gridLayout_4, 2, 0, 1, 5)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 0, 1, 1, 1)
        self.gridLayout_5.setColumnMinimumWidth(0, 220)
        self.gridLayout_5.setColumnMinimumWidth(2, 180)
        self.gridLayout_5.setColumnMinimumWidth(4, 300)
        self.gridLayout_5.setRowMinimumHeight(0, 220)
        Upgrade_Tool.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Upgrade_Tool)
        self.statusbar.setObjectName("statusbar")
        Upgrade_Tool.setStatusBar(self.statusbar)
        self.actionCAN_Open = QtWidgets.QAction(Upgrade_Tool)
        self.actionCAN_Open.setObjectName("actionCAN_Open")
        self.actionUART_Open = QtWidgets.QAction(Upgrade_Tool)
        self.actionUART_Open.setObjectName("actionUART_Open")
        self.actionTCP_Open = QtWidgets.QAction(Upgrade_Tool)
        self.actionTCP_Open.setObjectName("actionTCP_Open")

        self.retranslateUi(Upgrade_Tool)
        QtCore.QMetaObject.connectSlotsByName(Upgrade_Tool)

    def retranslateUi(self, Upgrade_Tool):
        _translate = QtCore.QCoreApplication.translate
        Upgrade_Tool.setWindowTitle(_translate("Upgrade_Tool", "MainWindow"))
        self.label_TCP.setText(_translate("Upgrade_Tool", "TCP链接"))
        self.label_IPPort.setText(_translate("Upgrade_Tool", "BCMU_端口"))
        self.lineEdit_IPAddr.setText(_translate("Upgrade_Tool", "192.168.1.100"))
        self.lineEdit_IPPort.setText(_translate("Upgrade_Tool", "6001"))
        self.label_IPAddr.setText(_translate("Upgrade_Tool", "BCMU_IP地址"))
        self.pushButton_TCPConnect.setText(_translate("Upgrade_Tool", "连接"))
        self.label_UART.setText(_translate("Upgrade_Tool", "UART链接"))
        self.pushButton_UARTConnect.setText(_translate("Upgrade_Tool", "连接"))
        self.pushButton_CheckPort.setText(_translate("Upgrade_Tool", "检查可用串口"))
        self.comboBox_Port.setItemText(0, _translate("Upgrade_Tool", "COM1"))
        self.comboBox_Port.setItemText(1, _translate("Upgrade_Tool", "COM2"))
        self.comboBox_Port.setItemText(2, _translate("Upgrade_Tool", "COM3"))
        self.comboBox_Port.setItemText(3, _translate("Upgrade_Tool", "COM4"))
        self.comboBox_Port.setItemText(4, _translate("Upgrade_Tool", "COM5"))
        self.comboBox_Port.setItemText(5, _translate("Upgrade_Tool", "COM6"))
        self.comboBox_Port.setItemText(6, _translate("Upgrade_Tool", "COM7"))
        self.comboBox_Port.setItemText(7, _translate("Upgrade_Tool", "COM8"))
        self.comboBox_Port.setItemText(8, _translate("Upgrade_Tool", "COM9"))
        self.comboBox_Port.setItemText(9, _translate("Upgrade_Tool", "COM10"))
        self.comboBox_Port.setItemText(10, _translate("Upgrade_Tool", "COM11"))
        self.comboBox_Port.setItemText(11, _translate("Upgrade_Tool", "COM12"))
        self.comboBox_Port.setItemText(12, _translate("Upgrade_Tool", "COM13"))
        self.comboBox_Port.setItemText(13, _translate("Upgrade_Tool", "COM14"))
        self.comboBox_Port.setItemText(14, _translate("Upgrade_Tool", "COM15"))
        self.comboBox_StopBit.setItemText(0, _translate("Upgrade_Tool", "1"))
        self.comboBox_StopBit.setItemText(1, _translate("Upgrade_Tool", "2"))
        self.label_PortSelect.setText(_translate("Upgrade_Tool", "串口选择："))
        self.comboBox_BoundRate.setItemText(0, _translate("Upgrade_Tool", "9600"))
        self.comboBox_BoundRate.setItemText(1, _translate("Upgrade_Tool", "19200"))
        self.comboBox_BoundRate.setItemText(2, _translate("Upgrade_Tool", "115200"))
        self.comboBox_CRCBit.setItemText(0, _translate("Upgrade_Tool", "NONE"))
        self.comboBox_CRCBit.setItemText(1, _translate("Upgrade_Tool", "EVEN"))
        self.comboBox_CRCBit.setItemText(2, _translate("Upgrade_Tool", "ODD"))
        self.comboBox_CRCBit.setItemText(3, _translate("Upgrade_Tool", "MARK"))
        self.comboBox_CRCBit.setItemText(4, _translate("Upgrade_Tool", "SPACE"))
        self.label_BoundRate.setText(_translate("Upgrade_Tool", "波特率："))
        self.label_Bit.setText(_translate("Upgrade_Tool", "数据位："))
        self.label_CRCBit.setText(_translate("Upgrade_Tool", "检验位"))
        self.label_StopBit.setText(_translate("Upgrade_Tool", "停止位："))
        self.comboBox_Bit.setItemText(0, _translate("Upgrade_Tool", "8"))
        self.comboBox_Bit.setItemText(1, _translate("Upgrade_Tool", "8.5"))
        self.comboBox_Bit.setItemText(2, _translate("Upgrade_Tool", "9"))
        self.label_CAN.setText(_translate("Upgrade_Tool", "CAN链接"))
        self.pushButton_CANConnect.setText(_translate("Upgrade_Tool", "连接"))
        self.comboBox_CANDevice.setItemText(0, _translate("Upgrade_Tool", "USBCAN2"))
        self.comboBox_CANDevice.setItemText(1, _translate("Upgrade_Tool", "USBCAN1"))
        self.comboBox_CANBoundRate.setItemText(0, _translate("Upgrade_Tool", "10Kbps"))
        self.comboBox_CANBoundRate.setItemText(1, _translate("Upgrade_Tool", "50Kbps"))
        self.comboBox_CANBoundRate.setItemText(2, _translate("Upgrade_Tool", "100Kbps"))
        self.comboBox_CANBoundRate.setItemText(3, _translate("Upgrade_Tool", "125Kbps"))
        self.comboBox_CANBoundRate.setItemText(4, _translate("Upgrade_Tool", "200Kbps"))
        self.comboBox_CANBoundRate.setItemText(5, _translate("Upgrade_Tool", "250Kbps"))
        self.comboBox_CANBoundRate.setItemText(6, _translate("Upgrade_Tool", "500Kbps"))
        self.comboBox_CANBoundRate.setItemText(7, _translate("Upgrade_Tool", "1000Kbps"))
        self.label_CANChannel.setText(_translate("Upgrade_Tool", "通道号"))
        self.comboBox_CANChannel.setItemText(0, _translate("Upgrade_Tool", "0"))
        self.comboBox_CANChannel.setItemText(1, _translate("Upgrade_Tool", "1"))
        self.label_CANBoundRate.setText(_translate("Upgrade_Tool", "波特率"))
        self.comboBox_CANIndex.setItemText(0, _translate("Upgrade_Tool", "0"))
        self.comboBox_CANIndex.setItemText(1, _translate("Upgrade_Tool", "1"))
        self.comboBox_CANIndex.setItemText(2, _translate("Upgrade_Tool", "2"))
        self.comboBox_CANIndex.setItemText(3, _translate("Upgrade_Tool", "3"))
        self.comboBox_CANIndex.setItemText(4, _translate("Upgrade_Tool", "4"))
        self.comboBox_CANIndex.setItemText(5, _translate("Upgrade_Tool", "5"))
        self.comboBox_CANIndex.setItemText(6, _translate("Upgrade_Tool", "6"))
        self.comboBox_CANIndex.setItemText(7, _translate("Upgrade_Tool", "7"))
        self.label_CANDevice.setText(_translate("Upgrade_Tool", "CAN设备"))
        self.label_CANIndex.setText(_translate("Upgrade_Tool", "设备索引号"))
        self.label_FileVersion.setText(_translate("Upgrade_Tool", "文件版本："))
        self.checkBox_Module5.setText(_translate("Upgrade_Tool", "5号模块"))
        self.checkBox_Module20.setText(_translate("Upgrade_Tool", "20号模块"))
        self.label_FileSize.setText(_translate("Upgrade_Tool", "文件大小："))
        self.checkBox_Module17.setText(_translate("Upgrade_Tool", "17号模块"))
        self.checkBox_Module16.setText(_translate("Upgrade_Tool", "16号模块"))
        self.label_Load.setText(_translate("Upgrade_Tool", "升级文件路径："))
        self.checkBox_Module18.setText(_translate("Upgrade_Tool", "18号模块"))
        self.checkBox_Module9.setText(_translate("Upgrade_Tool", "9号模块"))
        self.checkBox_AllUp.setText(_translate("Upgrade_Tool", "全部升级"))
        self.pushButton_StartUpgrade.setText(_translate("Upgrade_Tool", "开始升级"))
        self.checkBox_Module3.setText(_translate("Upgrade_Tool", "3号模块"))
        self.checkBox_Module11.setText(_translate("Upgrade_Tool", "11号模块"))
        self.checkBox_SelectAll.setText(_translate("Upgrade_Tool", "全选"))
        self.checkBox_Module10.setText(_translate("Upgrade_Tool", "10号模块"))
        self.checkBox_Module12.setText(_translate("Upgrade_Tool", "12号模块"))
        self.label_FileCRC.setText(_translate("Upgrade_Tool", "文件CRC校验："))
        self.checkBox_Module7.setText(_translate("Upgrade_Tool", "7号模块"))
        self.checkBox_Module13.setText(_translate("Upgrade_Tool", "13号模块"))
        self.checkBox_Module8.setText(_translate("Upgrade_Tool", "8号模块"))
        self.comboBox_SelcectZC.setItemText(0, _translate("Upgrade_Tool", "主控BCMU"))
        self.comboBox_SelcectZC.setItemText(1, _translate("Upgrade_Tool", "从控BMU"))
        self.checkBox_Module19.setText(_translate("Upgrade_Tool", "19号模块"))
        self.checkBox_Module4.setText(_translate("Upgrade_Tool", "4号模块"))
        self.pushButton_OpenFile.setText(_translate("Upgrade_Tool", "打开升级文件"))
        self.checkBox_Module2.setText(_translate("Upgrade_Tool", "2号模块"))
        self.checkBox_Module6.setText(_translate("Upgrade_Tool", "6号模块"))
        self.checkBox_Module15.setText(_translate("Upgrade_Tool", "15号模块"))
        self.checkBox_OneUp.setText(_translate("Upgrade_Tool", "单机升级"))
        self.checkBox_Module14.setText(_translate("Upgrade_Tool", "14号模块"))
        self.checkBox_Module1.setText(_translate("Upgrade_Tool", "1号模块"))
        self.pushButton_SaveRecord.setText(_translate("Upgrade_Tool", "保存日志"))
        self.textBrowser_UpgradeRecord.setHtml(_translate("Upgrade_Tool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">日志：</p></body></html>"))
        self.label_CommInfo.setText(_translate("Upgrade_Tool", "通讯设备信息：未打开"))
        self.actionCAN_Open.setText(_translate("Upgrade_Tool", "CAN_Open"))
        self.actionUART_Open.setText(_translate("Upgrade_Tool", "UART_Open"))
        self.actionTCP_Open.setText(_translate("Upgrade_Tool", "TCP_Open"))
