# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CSPZ.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QMessageBox,QInputDialog,QLineEdit
import Data
import JCCP_UI


Data_Temp = [0 for i in range(15)]

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(617, 480)
        self.gridLayout_8 = QtWidgets.QGridLayout(Form)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_4.addWidget(self.lineEdit_7, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_4.addWidget(self.lineEdit_8, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_5.addWidget(self.lineEdit_10, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_5.addWidget(self.lineEdit_9, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 4, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_11 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 0, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_6.addWidget(self.lineEdit_11, 0, 3, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_6.addWidget(self.lineEdit_12, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 5, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_7.addWidget(self.lineEdit_13, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_7.addWidget(self.lineEdit_14, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 6, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_9.addWidget(self.lineEdit_17, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_9.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_9.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 7, 0, 1, 1)

        self.retranslateUi(Form)
        self.Data_Init()
        self.pushButton.clicked.connect(self.Data_Write)
        self.pushButton_2.clicked.connect(self.Widgets_Close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def Data_Init(self):
        line_num = 0
        try:
            f = open(".\Deault_Par.txt")  # 返回一个文件对象
            for line in f.readlines():
                CurLine = line
                temp = int(CurLine)
                Data.Standard_Dict_Write(line_num,temp)
                line_num += 1
                if line_num> 14:
                    break
            f.close()

        except:
            QMessageBox.information(self,"错误信息","打开配置文件失败，使用默认配置参数",QMessageBox.Yes )

        self.lineEdit.setText(str(Data.Standard_Dict_Read(0)))
        self.lineEdit_2.setText(str(Data.Standard_Dict_Read(1)))
        self.lineEdit_4.setText(str(Data.Standard_Dict_Read(2)))
        self.lineEdit_3.setText(str(Data.Standard_Dict_Read(3)))
        self.lineEdit_8.setText(str(Data.Standard_Dict_Read(4)))
        self.lineEdit_7.setText(str(Data.Standard_Dict_Read(5)))
        self.lineEdit_6.setText(str(Data.Standard_Dict_Read(6)))
        self.lineEdit_5.setText(str(Data.Standard_Dict_Read(7)))
        self.lineEdit_10.setText(str(Data.Standard_Dict_Read(8)))
        self.lineEdit_9.setText(str(Data.Standard_Dict_Read(9)))
        self.lineEdit_12.setText(str(Data.Standard_Dict_Read(10)))
        self.lineEdit_11.setText(str(Data.Standard_Dict_Read(11)))
        self.lineEdit_14.setText(str(Data.Standard_Dict_Read(12)))
        self.lineEdit_13.setText(str(Data.Standard_Dict_Read(13)))
        self.lineEdit_17.setText(str(Data.Standard_Dict_Read(14)))

    def Str2Int(self,Data_n):
        try:
            temp = int(Data_n)
            return temp
        except:
            QMessageBox.information(self,"错误信息","不识别的数据类型",QMessageBox.Yes )
            return 0

    def Data_Write(self):

        value, ok = QInputDialog.getText(self, "请输入密码", "请输入密码:", QLineEdit.Normal, "******")
        if value != 'PD75JCV07':
            QMessageBox.information(self,"错误信息","密码错误",QMessageBox.Yes )
            self.close()

        temp = self.lineEdit.text()
        temp = self.Str2Int(temp)
        temp2 = self.lineEdit_2.text()
        temp2 = self.Str2Int(temp2)
        if temp != 0 and temp2 != 0:
            if temp >= temp2:
                QMessageBox.information(self,"错误信息","总电压下限大于上限",QMessageBox.Yes )
                return
        else:
            return
        Data_Temp[0] = temp
        Data_Temp[1] = temp2

        temp = self.lineEdit_4.text()
        temp = self.Str2Int(temp)
        temp2 = self.lineEdit_3.text()
        temp2 = self.Str2Int(temp2)
        if temp != 0 and temp2 != 0:
            if temp >= temp2:
                QMessageBox.information(self,"错误信息","单体电压下限大于上限",QMessageBox.Yes )
                return
        else:
            return
        Data_Temp[2] = temp
        Data_Temp[3] = temp2

        temp = self.lineEdit_8.text()
        temp = self.Str2Int(temp)
        temp2 = self.lineEdit_7.text()
        temp2 = self.Str2Int(temp2)
        if temp != 0 and temp2 != 0:
            if temp >= temp2:
                QMessageBox.information(self,"错误信息","单体温度下限大于上限",QMessageBox.Yes )
                return
        else:
            return
        Data_Temp[4] = temp
        Data_Temp[5] = temp2

        temp = self.lineEdit_6.text()
        temp = self.Str2Int(temp)
        temp2 = self.lineEdit_5.text()
        temp2 = self.Str2Int(temp2)
        if temp != 0 and temp2 != 0:
            if temp >= temp2:
                QMessageBox.information(self,"错误信息","SOC下限大于上限",QMessageBox.Yes )
                return
        else:
            return
        Data_Temp[6] = temp
        Data_Temp[7] = temp2

        temp = self.lineEdit_10.text()
        temp = self.Str2Int(temp)
        temp2 = self.lineEdit_9.text()
        temp2 = self.Str2Int(temp2)
        if temp != 0 and temp2 != 0:
            if temp >= temp2:
                QMessageBox.information(self,"错误信息","满充容量下限大于上限",QMessageBox.Yes )
                return
        else:
            return
        Data_Temp[8] = temp
        Data_Temp[9] = temp2

        temp = self.lineEdit_12.text()
        temp = self.Str2Int(temp)
        temp2 = self.lineEdit_11.text()
        temp2 = self.Str2Int(temp2)
        if temp != 0 and temp2 != 0:
            if temp >= temp2:
                QMessageBox.information(self,"错误信息","剩余容量下限大于上限",QMessageBox.Yes )
                return
        else:
            return
        Data_Temp[10] = temp
        Data_Temp[11] = temp2

        temp = self.lineEdit_14.text()
        temp = self.Str2Int(temp)
        temp2 = self.lineEdit_13.text()
        temp2 = self.Str2Int(temp2)
        if temp != 0 and temp2 != 0:
            if temp >= temp2:
                QMessageBox.information(self,"错误信息","电流下限大于上限",QMessageBox.Yes )
                return
        else:
            return
        Data_Temp[12] = temp
        Data_Temp[13] = temp2


        temp = self.lineEdit_17.text()
        temp = self.Str2Int(temp)
        if temp != 0:
            Data_Temp[14] = temp

        f = open(".\Deault_Par.txt",'w')  # 返回一个文件对象
        for i in range(15):
            f.write(str(Data_Temp[i]))
            f.write('\n')
        f.write('\n')
        f.write('\n')
        f.write('\n')
        f.write('\n')
        f.write('/*PD75-JC-V07*/')
        f.close()
        JCCP_UI.Par_Charge_Flag = 1
        self.close()


    def Widgets_Close(self):
        self.close()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "标准值设置"))
        self.label.setText(_translate("Form", "总电压     "))
        self.label_2.setText(_translate("Form", "-"))
        self.label_15.setText(_translate("Form", "mV "))
        self.label_3.setText(_translate("Form", "单体电压"))
        self.label_4.setText(_translate("Form", "-"))
        self.label_16.setText(_translate("Form", "mV "))
        self.label_7.setText(_translate("Form", "单体温度"))
        self.label_8.setText(_translate("Form", "-"))
        self.label_18.setText(_translate("Form", "℃ "))
        self.label_6.setText(_translate("Form", "-"))
        self.label_5.setText(_translate("Form", "SOC              "))
        self.label_19.setText(_translate("Form", "%   "))
        self.label_9.setText(_translate("Form", "设计容量"))
        self.label_10.setText(_translate("Form", "-"))
        self.label_20.setText(_translate("Form", "mAh"))
        self.label_11.setText(_translate("Form", "剩余容量"))
        self.label_12.setText(_translate("Form", "-"))
        self.label_21.setText(_translate("Form", "mAh"))
        self.label_14.setText(_translate("Form", "-"))
        self.label_13.setText(_translate("Form", "总电流     "))
        self.label_22.setText(_translate("Form", "mA "))
        self.label_17.setText(_translate("Form", "版本号     "))
        self.pushButton.setText(_translate("Form", "确定"))
        self.pushButton_2.setText(_translate("Form", "取消"))

